on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
      - uses: Swatinem/rust-cache@v2  

      - uses: taiki-e/install-action@cargo-binstall
      - run: cargo binstall --no-confirm --force just
      - run: just check-all
